feat(project): add prisma workspace (#10)
* feat(project): add prisma workspace

* chore: add dotenv for development environment

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -40,7 +40,13 @@ jobs:
         run: yarn install --immutable --immutable-cache
       - name: Check formatting of project files
         run: yarn format:diff
-
+      - name: Check schema.prisma formatting
+        run: |
+          yarn prisma format
+          if [ -n "$(git status --porcelain)" ]; then
+          echo "::error:: Prisma schema is not formatted correctly. Please run yarn prisma format"
+            exit 1
+          fi
   lint:
     runs-on: ubuntu-latest
     steps:
@@ -53,3 +59,16 @@ jobs:
         run: yarn install --immutable --immutable-cache
       - name: Check formatting of project files
         run: yarn lint
+
+  prisma:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v3
+      - name: Use Node.js 16.x
+        uses: actions/setup-node@v3
+        with:
+          node-version: '16.x'
+      - name: Install dependencies
+        run: yarn install --immutable --immutable-cache
+      - name: Validate prisma schema
+        run: yarn dotenv -e .env.development prisma validate
